### PR TITLE
Fixed the height of Random Hero Button ,made search bar bigger and aligned 

### PR DESCRIPTION
**Pull request by harshhgithub**
Screenshot (144)

Please add hacktoberfest and hacktoberfest-accepted label also.
Thanks

### CODE REVIEW

**Comment by Prajwal0225** [comment]
can you make search bar little bigger and make random and Download btn properly align with it.

**Comment by harshhgithub** [comment]
Okay will make an another pull request regarding that . 
Can you merge this first ?
Add the labels too .
Thanks

**Comment by Prajwal0225** [comment]
Do the work. I will merge that one.
Merging for the same issue again and again I don't think necessary.

**Comment by harshhgithub** [comment]
Screenshot (145)

Aligned and made it bigger . Now it looks good

**Pull request merged**
