### PR TITLE
Creating download function and styling ui

### PR DESCRIPTION
**Pull request by samrat2k03**
i have made the changes in ui like styling 
- buttons ,
- input:search ,

& added the download functionality to download the image . please provide feedback

### CODE REVIEW

**Comment by Prajwal0225** [comment]
Please provide some screenshots of what you have done and resolve the conflicts.

**Comment by samrat2k03** [comment]
Screenshot (107)
Screenshot (108)
Screenshot (109)

**Comment by Prajwal0225** [comment]
The random hero button and Download button are not properly aligned can fix that and make a PR.

**Comment by Prajwal0225** [comment]
Thank you for your invaluable contributions to our open-source project! 🚀 If you like our project, please consider to start ⭐ the repo.

**Pull request merged**
