### PR TITLE
Loading message while fetching

### PR DESCRIPTION
**Pull request by nishaaannnt**
resolves the issue #41 

A loading message is displayed when the image is being fetched 

screenshot- 

Screenshot (234)

also error management is done to handle edge cases .

### CODE REVIEW

**Comment by nishaaannnt** [comment]
regarding the conflict just allow incoming changes as it will not affect the project in any way.
The loading had font style different then the theme of the website so i had to add the same font-family to it

**Comment by nishaaannnt** [comment]
hello @Prajwal0225 yeah sure i can do that.
i will make the necessary changes and let you know

**Comment by Prajwal0225** [comment]
> hello @Prajwal0225 yeah sure i can do that. i will make the necessary changes and let you know

Ok, to make the desired changes, please clone the repository again, as the website has undergone several modifications. Avoid working on the old clone.

**Comment by nishaaannnt** [comment]
hello @Prajwal0225 , made the necessary changes

Screenshot (237)

**Pull request closed without merging**
