### PR TITLE
fix: Enhanced Superhero Image Size for Better Aesthetics

### LINKED ISSUE #25: Enhance Superhero Image Size for Better Aesthetics
**Description:**
The current display of the superhero image after searching appears smaller and does not provide an attractive user experience. To improve the visual appeal of our project, we need to increase the size of the displayed image.

**Image :**
increase the image size

**Task Details:**
Increase the size of the displayed superhero image for better aesthetics.

### PR DESCRIPTION
**Pull request by vamsi-spoidey7**
fixes #25 
Changed the image size to 400px in script.js

Image after fix:
Screenshot 2023-10-02 112127

### CODE REVIEW

**Comment by vamsi-spoidey7** [comment]
I guess this looks fine

**Comment by Prajwal0225** [comment]
Thank you for your invaluable contributions to our open-source project! 🚀 If you like our project, please consider giving a star ⭐ to the repo.

**Comment by vamsi-spoidey7** [comment]
i personally like this project very much.

**Comment by Prajwal0225** [comment]
@vamsi-spoidey7 I think you made changes for one random superhero button when we search superhero my name image size is still small

image


image

**Please make widht:300px and height: 400px for both search and random search images.**

**Comment by vamsi-spoidey7** [comment]
will solve it

**Pull request merged**
