### PR TITLE
converted all values from px to rems.

### PR DESCRIPTION
**Pull request by divyansh14kr**
converted all px values to rem and set the base html font size to 16px.

### CODE REVIEW

**Comment by Prajwal0225** [comment]
Please resolve the conflicts.

**Comment by divyansh14kr** [comment]
converted the new values to rem, please revert back for any problems

**Comment by Prajwal0225** [comment]
Thank you for your invaluable contributions to our open-source project! 🚀 If you like our project, please consider to start ⭐ the repo.

**Comment by Prajwal0225** [comment]
Issue #18

**Pull request merged**
