### PR TITLE
html , css and javascript changes done

### PR DESCRIPTION
**Pull request by Hrishap**
1.title changed from "Supperhero's" to "Superhero"
original:
Screenshot 2023-10-01 183038
changed to:
Screenshot 2023-10-01 183059
2.font of whole text in the site changed
earlier:
Screenshot 2023-10-01 183346

changed to:
Screenshot 2023-10-01 183405

3.Hover effect added ,cursor changed into pointer on hovering ,width of input text also increased and border color also changed
earlier:
Screenshot 2023-10-01 183346

changed to:
Screenshot (929)

4.Some changes Javascripts code on clicking random hero button the text in input text box clears

earlier:
Screenshot (927)

changed to:
Screenshot (928)

### CODE REVIEW

**Comment by Prajwal0225** [comment]
Please remember that only pull requests assigned to specific issues will be considered in this repository. Avoid submitting pull requests directly 🙂.

Start by creating an issue, and once you're assigned to it, proceed with your work.

**Comment by Hrishap** [comment]
sorry sir for the inconvenience caused 
i will implement as per the your direction 
thank you sir for correcting me

**Comment by Hrishap** [comment]
Changes done according to the issue assigned

**Comment by Prajwal0225** [comment]
Please resolve the conflicts in style.css.

**Comment by Hrishap** [comment]
sorry for the  inconvenience all conflict resolved

**Comment by Prajwal0225** [comment]
Thank you for your invaluable contributions to our open-source project! 🚀 If you like our project, please consider to start ⭐ the repo.

**Pull request merged**
