### PR TITLE
feat: Added Lively Background Image

### PR DESCRIPTION
**Pull request by Priyanshume18**
Fixes#36
 Now the websit looks like :

git

### CODE REVIEW

**Comment by Prajwal0225** [comment]
It's not looking good can you try a different background

**Comment by Priyanshume18** [comment]
I tried many,but most of them makes the need to change the text colors also
Isn't it anyway good?
okay, letme try once more

**Comment by Priyanshume18** [comment]
what about this
image

**Comment by Priyanshume18** [comment]
on scrolling down ,complete view is this
image

**Pull request closed without merging**
