### PR TITLE
updated about page

### PR DESCRIPTION
**Pull request by shreyamaurya029**
I  have updated the about page, making some changes in html and css code of about

### CODE REVIEW

**Comment by Prajwal0225** [comment]
please resolve the conflicts.

**Review by Prajwal0225 — APPROVED** [review]

**Comment by Prajwal0225** [comment]
Thank you for your invaluable contributions to our open-source project! 🚀 If you like our project, please consider to start ⭐ the repo.

**Comment by Prajwal0225** [comment]
The design already looks great, but I believe there's an opportunity to make it even more remarkable. I was wondering if you'd be open to collaborating on some further enhancements to improve the UI.

image

**Comment by shreyamaurya029** [comment]
cool, i am fine with it

**Pull request merged**
