### PR TITLE
Added Logo to the Landing and Sub pages

### PR DESCRIPTION
**Pull request by VibhorGits**
This PR Adds a new Logo to the SuperHero Website on the landing as well as all the other subpages.

Added the relevant size to the logo as per the websites specifications.

### CODE REVIEW

**Comment by VibhorGits** [comment]
Hey @Prajwal0225 I have successful made a pr.
Do have a look and let me know if it require any more fixes

**Comment by Prajwal0225** [comment]
Can you try another style. Logo look soo simple.

**Comment by VibhorGits** [comment]
Ok I will try to add a layout or something similar

**Comment by VibhorGits** [comment]
Hey @Prajwal0225 
Have a look at the new logo here : https://github.com/Prajwal0225/My-Favorite-SuperHero/pull/298

**Comment by VibhorGits** [comment]
Hey @Prajwal0225 Any updates on the issue?

**Comment by madhurafulkar** [comment]
We didn't merge your pull request because we found your designed logo to be too simple.

**Pull request closed without merging**
