### PR TITLE
Resized the background image

### LINKED ISSUE #172: Resize the background image
Resize the background image (bg.jpg) to match the dimensions of the generated superhero image while ensuring that the button positions remain unchanged.

Anyone interested to work on it?

### PR DESCRIPTION
**Pull request by Pinaka-Pani-18**
closes #172 

Now, this is how it works

https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/102857774/daf4cc2a-41e1-42e5-8c9d-a2ee5c4bc0e6

### CODE REVIEW

**Comment by Prajwal0225** [comment]
Please resize this image ⤵️  not the hero image generated using API. 

image

You have to Resize the background image (bg.jpg) to match the dimensions of the generated superhero image

**Comment by Pinaka-Pani-18** [comment]
> Please resize this image ⤵️ not the hero image generated using API.
> 
> image
> 
> You have to Resize the background image (bg.jpg) to match the dimensions of the generated superhero image

Now can you check out, is it okay?

**Comment by Prajwal0225** [comment]
https://prajwal0225.github.io/My-Favorite-SuperHero/index.html

**Comment by Prajwal0225** [comment]
Thank you for your invaluable contributions to our open-source project! 🚀 If you like our project, please consider to start ⭐ the repo.

**Pull request merged**
