### PR TITLE
Making the navigation bar prettier

### PR DESCRIPTION
**Pull request by pushkar1713**
I have Created a responsive navigation bar with logo and a drop down feature for mobiles.

Fixes the issue [#75](https://github.com/Prajwal0225/My-Favorite-SuperHero/issues/75)

Please consider merging this pull request to the main branch. Please let me know if there are any problems as this is my first time using git and contributing to open source.

Before :
Screenshot 2023-10-04 at 6 34 05 PM

After :

Desktop:
Screenshot 2023-10-05 at 10 18 18 PM

Mobile:
InCollage_20231005_230215660

### CODE REVIEW

**Comment by Prajwal0225** [comment]
Can You try to design the nav bar like this https://codepen.io/kotasowa/pen/zNreoN

**Comment by Prajwal0225** [comment]
No worries you can refer that code

**Comment by pushkar1713** [comment]
Please tell me how do I resolve conflicts or should I just make a new branch and pr?

**Comment by pushkar1713** [comment]
Please tell me how do I resolve conflicts or should I just make a new branch and pr?

**Comment by pushkar1713** [comment]
> Can You try to design the nav bar like this https://codepen.io/kotasowa/pen/zNreoN And also add a temporary logo for now.

I have successfully implemented the advised changes, please merge this with the main request now

**Review by Prajwal0225 — APPROVED** [review]

**Pull request merged**
