### PR TITLE
design respnsive navigation bar,which has superhero logo ,home sectio…

### PR DESCRIPTION
**Pull request by Ir786921**
Design a Responsive navigation bar ,which has logo section,home section,about section,contributor section and finally user greeting section.

### CODE REVIEW

**Comment by Prajwal0225** [comment]
@Ir786921 
Please resolve the conflicts.

**Comment by Prajwal0225** [comment]
Could you please share a screenshot so that I can get a better idea of what you have done?

**Comment by Ir786921** [comment]
Screenshot (281)

**Comment by Prajwal0225** [comment]
Website screenshot of how the navbar is looking

**Comment by Ir786921** [comment]
Screenshot (282)
Screenshot (283)
Screenshot (284)

**Comment by Prajwal0225** [comment]
Could you please remove 'Hi, user' and place 'Home,' 'About,' and 'Contributors' on the right side,  It looks really good otherwise.

**Comment by Ir786921** [comment]
ok ,no problem i am doing it.

**Comment by Ir786921** [comment]
Screenshot (285)
 is it ok?

**Comment by Prajwal0225** [comment]
Perfect ✨

**Review by Prajwal0225 — APPROVED** [review]

**Comment by Prajwal0225** [comment]
Thank you for your invaluable contributions to our open-source project! 🚀 If you like our project, please consider to start ⭐ the repo.

**Comment by Prajwal0225** [comment]
I think CSS is not properly link it's showing link this 
image

please resolve this

**Comment by Prajwal0225** [comment]
Try to resolve this error and make a PR, after merging you PR website is showing some unexpected behaviour 

image


Logo size automatically gets increased try to fix this also

**Comment by Prajwal0225** [comment]
I removed your merged your PR so it is working fine now. but when adding your code it behaves unexpectedly.

**Pull request merged**
