### PR TITLE
Fixed the comment-on-issue workflow

### LINKED ISSUE #16: comment-on-issue.yml is not generating comment after issue get generated
comment-on-issue.yml is located at .github/workflows

### PR DESCRIPTION
**Pull request by akhilender-bongirwar**
- Changed few instances in code to ensure proper working of the workflows.
- With the current changes the comment-on-issue raised should work properly.
- Fixes #16

### CODE REVIEW

**Comment by akhilender-bongirwar** [comment]
Hey @Prajwal0225, please make sure you have the necessary GitHub Actions permissions and that you have correctly configured GitHub Secrets to include the 'GitHub token' for the workflows to function properly.

**Comment by Prajwal0225** [comment]
Do not delete the repository until your pull request (PR) is merged. This will close the PR automatically.

**Comment by akhilender-bongirwar** [comment]
@Prajwal0225, sorry I didn't know that. what should I be doing now?

**Comment by Prajwal0225** [comment]
You have to make a PR again😅.

**Comment by akhilender-bongirwar** [comment]
@Prajwal0225, could you please ensure whether the comment on issue workflow is working properly : )

**Comment by Prajwal0225** [comment]
Yaa, but for that someone has to create an issue on this repo other than owner 😅 
can you please create a dummy issue so that we get the idea if it is woking or not

**Comment by akhilender-bongirwar** [comment]
@Prajwal0225, I think it is not working but the code is wrote is valid code. Could you please make sure you have the necessary GitHub Actions permissions and that you have correctly configured GitHub Secrets to include the 'GitHub token' for the workflows to function properly.

**Comment by Prajwal0225** [comment]
ook I will check it

**Pull request closed without merging**
